version: 2

project_name: unterlumen

before:
  hooks:
    - sh -c "cd src && go mod tidy"

builds:
  - dir: src
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w -X main.Version={{ .Version }}

archives:
  - formats: [tar.gz]
    format_overrides:
      - goos: windows
        formats: [zip]
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}_{{ if eq .Os "darwin" }}{{ if eq .Arch "amd64" }}intel{{ else }}apple_silicon{{ end }}{{ else }}{{ .Arch }}{{ end }}'

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^doc:'
      - '^chore:'
