unterlumen.repository.location=/tmp/unterlumen/repository
unterlumen.cache.location=/tmp/unterlumen/cache

%dev.quarkus.hibernate-orm.database.generation=update
%dev.quarkus.datasource.db-kind=h2
%dev.quarkus.datasource.jdbc.url=jdbc:h2:file:/tmp/unterlumen/index;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
%dev.quarkus.datasource.jdbc.driver=org.h2.Driver
%dev.quarkus.datasource.username=sa
%dev.quarkus.datasource.password=sa

%test.quarkus.hibernate-orm.database.generation=update
%test.quarkus.datasource.db-kind=h2
%test.quarkus.datasource.jdbc.url=jdbc:h2:file:/tmp/unterlumen/index;DB_CLOSE_DELAY=-1
%test.quarkus.datasource.jdbc.driver=org.h2.Driver
%test.quarkus.datasource.username=sa
%test.quarkus.datasource.password=sa